export const marketlar = [
  // Offline supermarketlar
  { id: 1, value: "korzinka", label: "Korzinka" },
  { id: 2, value: "makro", label: "Makro" },
  { id: 3, value: "carrefour", label: "Carrefour" },
  { id: 4, value: "havas", label: "Havas" },
  { id: 5, value: "magnum", label: "Magnum" },
  { id: 6, value: "bi1", label: "Bi1" },
  { id: 7, value: "globus", label: "Globus" },
  { id: 8, value: "malika", label: "Malika Market" },
  { id: 9, value: "askar", label: "Askar Market" },
  { id: 10, value: "grand", label: "Grand Market" },

  // Online do‘konlar
  { id: 11, value: "olcha", label: "Olcha.uz" },
  { id: 12, value: "mediapark", label: "Mediapark" },
  { id: 13, value: "goodzone", label: "Goodzone" },
  { id: 14, value: "texnomart", label: "Texnomart" },
  { id: 15, value: "asaxiy", label: "Asaxiy.uz" },
  { id: 16, value: "zoodmall", label: "ZoodMall" },
  { id: 17, value: "uzum", label: "Uzum Market" },
  { id: 18, value: "express24", label: "Express24" },
  { id: 19, value: "chopar", label: "Chopar" },
  { id: 20, value: "bookcafe", label: "BookCafe.uz" },
];


export const viloyatlar = [
    { id: 7, value: "namangan", label: "Namangan" },
  { id: 1, value: "toshkent_sh", label: "Toshkent shahar" },
  { id: 2, value: "toshkent", label: "Toshkent viloyati" },
  { id: 3, value: "andijon", label: "Andijon" },
  { id: 4, value: "buxoro", label: "Buxoro" },
  { id: 5, value: "fargona", label: "Fargʻona" },
  { id: 6, value: "jizzax", label: "Jizzax" },
  { id: 8, value: "navoiy", label: "Navoiy" },
  { id: 9, value: "qashqadaryo", label: "Qashqadaryo" },
  { id: 10, value: "qoraqalpogiston", label: "Qoraqalpogʻiston R." },
  { id: 11, value: "samarqand", label: "Samarqand" },
  { id: 12, value: "sirdaryo", label: "Sirdaryo" },
  { id: 13, value: "surxondaryo", label: "Surxondaryo" },
  { id: 14, value: "xorazm", label: "Xorazm" },
];

export const statusOptions = [
  { value: "new", label: "NEW" },
  { value: "received", label: "RECEIVED"},
  { value: "on_the_road", label: "ON THE ROAD"},
  { value: "waiting", label: "WAITING"},
  { value: "sold", label: "SOLD"},
  { value: "cancelled", label: "CANCELLED"},
  { value: "paid", label: "PAID", color: "cyan" },
  { value: "partly_paid", label: "PARTLY PAID"},
  { value: "cancelled_sent", label: "CANCELLED (SENT)"},
  { value: "closed", label: "CLOSED"},
];

export const OrderData = [
  {
    id: 1,
    customer: "John Doe",
    phone: "+998 90 123 45 67",
    address: "Toshkent shahar, Yunusobod",
    market: "Korzinka",
    status: "new",
    price: "1,200,000 UZS",
    stock: 15,
  },
  {
    id: 2,
    customer: "Alice Smith",
    phone: "+998 91 765 43 21",
    address: "Samarqand, Registon",
    market: "Makro",
    status: "paid",
    price: "850,000 UZS",
    stock: 8,
  },
  {
    id: 3,
    customer: "Bob Johnson",
    phone: "+998 99 111 22 33",
    address: "Buxoro, Gijduvon",
    market: "Carrefour",
    status: "on_the_road",
    price: "2,400,000 UZS",
    stock: 3,
  },
  {
    id: 4,
    customer: "Emma Watson",
    phone: "+998 97 444 55 66",
    address: "Andijon, Asaka",
    market: "Havas",
    status: "cancelled",
    price: "500,000 UZS",
    stock: 0,
  },
  {
    id: 5,
    customer: "Michael Brown",
    phone: "+998 95 321 76 54",
    address: "Namangan, Chortoq",
    market: "Magnum",
    status: "sold",
    price: "3,100,000 UZS",
    stock: 12,
  },
  {
    id: 6,
    customer: "Sophia Lee",
    phone: "+998 93 222 44 55",
    address: "Fargʻona, Margʻilon",
    market: "Bi1",
    status: "waiting",
    price: "1,750,000 UZS",
    stock: 6,
  },
  {
    id: 7,
    customer: "David Miller",
    phone: "+998 94 777 88 99",
    address: "Xorazm, Urganch",
    market: "Globus",
    status: "received",
    price: "2,850,000 UZS",
    stock: 9,
  },
  {
    id: 8,
    customer: "Olivia Davis",
    phone: "+998 90 555 66 77",
    address: "Qashqadaryo, Qarshi",
    market: "Malika Market",
    status: "partly_paid",
    price: "920,000 UZS",
    stock: 4,
  },
  {
    id: 9,
    customer: "James Wilson",
    phone: "+998 97 888 99 00",
    address: "Surxondaryo, Termiz",
    market: "Olcha.uz",
    status: "cancelled_sent",
    price: "1,450,000 UZS",
    stock: 2,
  },
  {
    id: 10,
    customer: "Isabella Martinez",
    phone: "+998 99 333 44 55",
    address: "Jizzax, Zomin",
    market: "Asaxiy.uz",
    status: "closed",
    price: "670,000 UZS",
    stock: 5,
  },
];
